<?php

$state_list = array (
    'all' => 'All',
    'AL' => 'Alabama',
    'AK' => 'Alaska',
    'AS' => 'American Samoa',
    'AZ' => 'Arizona',
    'AR' => 'Arkansas',
    'CA' => 'California',
    'CO' => 'Colorado',
    'CT' => 'Connecticut',
    'DE' => 'Delaware',
    'DC' => 'D.C.',
    'FL' => 'Florida',
    'GA' => 'Georgia',
    'GU' => 'Guam',
    'HI' => 'Hawaii',
    'ID' => 'Idaho',
    'IL' => 'Illinois',
    'IN' => 'Indiana',
    'IA' => 'Iowa',
    'KS' => 'Kansas',
    'KY' => 'Kentucky',
    'LA' => 'Louisiana',
    'ME' => 'Maine',
    'MD' => 'Maryland',
    'MA' => 'Massachusetts',
    'MI' => 'Michigan',
    'MN' => 'Minnesota',
    'MS' => 'Mississippi',
    'MO' => 'Missouri',
    'MT' => 'Montana',
    'NE' => 'Nebraska',
    'NV' => 'Nevada',
    'NH' => 'New Hampshire',
    'NJ' => 'New Jersey',
    'NM' => 'New Mexico',
    'NY' => 'New York',
    'NC' => 'North Carolina',
    'ND' => 'North Dakota',
    'OH' => 'Ohio',
    'OK' => 'Oklahoma',
    'OR' => 'Oregon',
    'PA' => 'Pennsylvania',
    'PR' => 'Puerto Rico',
    'RI' => 'Rhode Island',
    'SC' => 'South Carolina',
    'SD' => 'South Dakota',
    'TN' => 'Tennessee',
    'TX' => 'Texas',
    'UT' => 'Utah',
    'VT' => 'Vermont',
    'VI' => 'Virgin Islands',
    'VA' => 'Virginia',
    'WA' => 'Washington',
    'WV' => 'West Virginia',
    'WI' => 'Wisconsin',
    'WY' => 'Wyoming'
);


$osm_state_list = '
      <li id="state-all">All</li>
      <li id="state-AL">Alabama</li>
      <li id="state-AK">Alaska</li>
      <li id="state-AS">American Samoa</li>
      <li id="state-AZ">Arizona</li>
      <li id="state-AR">Arkansas</li>
      <li id="state-CA">California</li>
      <li id="state-CO">Colorado</li>
      <li id="state-CT">Connecticut</li>
      <li id="state-DE">Delaware</li>
      <li id="state-DC">D.C.</li>
      <li id="state-FL">Florida</li>
      <li id="state-GA">Georgia</li>
      <li id="state-GU">Guam</li>
      <li id="state-HI">Hawaii</li>
      <li id="state-ID">Idaho</li>
      <li id="state-IL">Illinois</li>
      <li id="state-IN">Indiana</li>
      <li id="state-IA">Iowa</li>
      <li id="state-KS">Kansas</li>
      <li id="state-KY">Kentucky</li>
      <li id="state-LA">Louisiana</li>
      <li id="state-ME">Maine</li>
      <li id="state-MD">Maryland</li>
      <li id="state-MA">Massachusetts</li>
      <li id="state-MI">Michigan</li>
      <li id="state-MN">Minnesota</li>
      <li id="state-MS">Mississippi</li>
      <li id="state-MO">Missouri</li>
      <li id="state-MT">Montana</li>
      <li id="state-NE">Nebraska</li>
      <li id="state-NV">Nevada</li>
      <li id="state-NH">New Hampshire</li>
      <li id="state-NJ">New Jersey</li>
      <li id="state-NM">New Mexico</li>
      <li id="state-NY">New York</li>
      <li id="state-NC">North Carolina</li>
      <li id="state-ND">North Dakota</li>
      <li id="state-OH">Ohio</li>
      <li id="state-OK">Oklahoma</li>
      <li id="state-OR">Oregon</li>
      <li id="state-PA">Pennsylvania</li>
      <li id="state-PR">Puerto Rico</li>
      <li id="state-RI">Rhode Island</li>
      <li id="state-SC">South Carolina</li>
      <li id="state-SD">South Dakota</li>
      <li id="state-TN">Tennessee</li>
      <li id="state-TX">Texas</li>
      <li id="state-UT">Utah</li>
      <li id="state-VT">Vermont</li>
      <li id="state-VI">Virgin Islands</li>
      <li id="state-VA">Virginia</li>
      <li id="state-WA">Washington</li>
      <li id="state-WV">West Virginia</li>
      <li id="state-WI">Wisconsin</li>
      <li id="state-WY">Wyoming</li>
     ';

